# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnoses',
            fields=[
                ('diagnosesID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('diagnosesName', models.TextField()),
                ('diagnosesDateBegin', models.DateTimeField()),
                ('diagnosesDateEND', models.DateTimeField()),
                ('diagnosesSeverity', models.PositiveIntegerField()),
            ],
        ),
    ]
