# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointmentID', models.PositiveIntegerField(max_length=250, primary_key=True, serialize=False)),
                ('scheduledDate', models.DateField()),
                ('scheduledTime', models.DateTimeField()),
                ('notes', models.TextField()),
                ('checkinTime', models.DateTimeField()),
                ('checkoutTime', models.DateTimeField()),
                ('appointmentStart', models.DateTimeField()),
                ('appointmentEnd', models.DateTimeField()),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Employee')),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
            ],
        ),
    ]
