# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientID', models.PositiveIntegerField(max_length=250, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('middleI', models.CharField(max_length=1, null=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('fileKey', models.CharField(max_length=30, null=True)),
                ('maritalStat', models.CharField(max_length=30, null=True)),
                ('phone', models.PositiveIntegerField(max_length=11, null=True)),
                ('occupation', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mailingAdd', models.CharField(max_length=250)),
                ('children', models.PositiveIntegerField(max_length=30)),
                ('medicalHistory', models.TextField()),
            ],
        ),
    ]
